### PR TITLE
fix: scope plugin

### LINKED ISSUE #22: Scope plugin to avoid actions outside scope

### PR DESCRIPTION
**Pull request by spaenleh**
This PR adds scope to the plugin so that the OnSend hook does not interfere with the other parts of fastify.

closes #22

### CODE REVIEW

File: src/service-api.ts [hunk 1]
```diff
@@ -46,112 +47,117 @@ const plugin: FastifyPluginAsync<GraaspChatPluginOptions> = async (
...
-  );
-
-  fastify.decorate('chat', { dbService: chatService, taskManager });
-
-  fastify.addSchema(common);
-
-  // register websocket behaviours for chats
-  if (websockets) {
-    registerChatWsHooks(
+  fastify.register(async function (fastify) {
```
Comment (pyphilia) [inline src/service-api.ts:50]: Add a comment why we needed it!

**Review by pyphilia — APPROVED** [review]
